title: Hujiang's homepage
logo: /assets/img/hujiang.jpg
description: Ph.D. candidate from Peking University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
address:
  - line: Beijing International Center for Mathematical Research, Peking University
  - line: No. 5 Yiheyuan Road Haidian District, Beijing, P.R.China 100871
