title: Difan Yuan
logo: /assets/img/Difan Yuan.jpg
description: Ph.D. candidate at University of Chinese Academy of Sciences
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
address:
  - line: No.55, Zhong GuanCun East Road, Academy of Mathematics and Systems Science
  - line: UCAS, Beijing, 100190
